# Jekyll configuration
title: Mark Shaneck
#email: nope
description: Musings on security and education
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://markshaneck.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: mshaneck
github_username:  mshaneck
name: Mark Shaneck


# This can be '' to hide the Github nav button
github: ''

# Set this to your UA-# value, or '' to disable the block completely
gaaccount: 'UA-104272008-1'

# The 'comments' setting enables comments. You'll need to select either
# disqus or isso below to choose a comment system. Individual posts can
# override 'comments' to disable on a post-by-post basis.
comments: false

# Set this to your public isso URL to enable comments via isso. Set to '' to disable isso.
isso: ''

# Set this to your disqus shortname to enable comments via disqus. Set to '' to disable disqus.
disqus: ''

#permalink: /:year/:month/:title
paginate: 3

highlighter: rouge
markdown: kramdown

exclude: ['README.md', 'LICENSE']

plugins:
      - jekyll-feed
      - jekyll-paginate

